#! /bin/sh

cd /home/pi/Documents/DinnerTimePi/

case "$1" in
	start)
		java -jar DinnerTimeServer.jar
	;;
	stop)
		pid=`ps -aux | grep DinnerTime | awk '{print $2}'`
		sudo kill -9 $pid
	;;
	*)
		java -jar DinnerTimeServer.jar
	;;
esac

exit 0
